### ISSUE TITLE
Why are you modifying core files?

### ISSUE THREAD

**Issue by skione** [fballiano/magento-cache-regeneration-lock#2]
Dude, 

You are a certified developer, why are you modding core files?

**Comment by fballiano** [comment]
it's written in the readme.

sent from phone

Il 19 gen 2018 02:56, "Michael Sole" <notifications@github.com> ha scritto:

**Comment by GreenGinkgo** [comment]
Hi there! My understanding is that Magento ignores app/code/core files if there's a corresponding app/code/local file instead. So the question still stands: why does the patch make an edit to app/code/core/Mage/Core/Model/App.php when the previous step is to copy that file to app/code/local/Mage/Core/Model/App.php?

**Comment by fballiano** [comment]
if you copy the file in "local" and patch it you will 99% forget about it and when you'll upgrade magento that file is gonna stay old and modified, possibly causing problems or incompatibilities, anyway not a good way of maintaining your installation.

every case is different, for this specific patch there's absolutely no benefit in copying the file in local.
- you should remember to check your "local" modified file at any upgrade OR
- you should re-apply the patch after any upgrade
the second is a much safer thing, if you forget you've a default magento, no problems there. but in the first way you may end up with mixed files from different releases, very bad idea.

plus, should I release a different patched file for any magento version forever? it's simply impossibile, in the way I did it it's compatible with all versions without any work from my side.
